LICENSE
README.md

add LICENSE and update README.md

---

src/ch/blinkenlights/android/vanilla/PlaybackService.java

Fix #143 Android Lollipop: Lock screen widget improvement

---

src/ch/blinkenlights/android/vanilla/FullPlaybackActivity.java
src/ch/blinkenlights/android/vanilla/PlaybackActivity.java

Made performAction in FullPlaybackActivity override it.
This fixes the bug #44 where swipe up/down was not toggling controls when that preference was set
I don't know much about the code base, so please let me know if this isn't an appropriate solution :)

Added performAction in PlaybackActivity. 

---

res/layout/listview.xml
src/ch/blinkenlights/android/vanilla/MediaAdapter.java

Add fast-scroller and implement on-cursor-change section indexer for MediaAdapter
Works flawlessly on Songs/Albums/Genres tabs

Add fast-scroll indexer to MediaAdapter (Library View)

---

res/values-ru/translatable.xml
res/values/translatable.xml
res/xml/preference_library.xml
src/ch/blinkenlights/android/vanilla/LibraryActivity.java
src/ch/blinkenlights/android/vanilla/LibraryPagerAdapter.java
src/ch/blinkenlights/android/vanilla/MediaUtils.java
src/ch/blinkenlights/android/vanilla/PrefDefaults.java
src/ch/blinkenlights/android/vanilla/PrefKeys.java

Implement scroll-to-song and option in menu

---

res/values-ru/translatable.xml
res/values/translatable.xml
src/ch/blinkenlights/android/vanilla/FullPlaybackActivity.java
src/ch/blinkenlights/android/vanilla/MediaUtils.java
src/ch/blinkenlights/android/vanilla/PlaybackActivity.java

Implement share action in Library & NowPlaying

---

res/values/translatable.xml
src/ch/blinkenlights/android/vanilla/LibraryActivity.java
src/ch/blinkenlights/android/vanilla/PluginUtils.java

Plugin subsystem. Shown as a last option in song context menu. 

---

src/ch/blinkenlights/android/vanilla/FullPlaybackActivity.java
src/ch/blinkenlights/android/vanilla/LibraryActivity.java
src/ch/blinkenlights/android/vanilla/PlaybackActivity.java

- refactor plugin querying in a way that now any
library activity can utilize it
- Make doc more thorough
- Hopefully fix empty plugin list bug
(flag was added to wrong intent)

Add "plugins" menu option in full playback view

---

res/values/translatable.xml
src/ch/blinkenlights/android/vanilla/FileSystemAdapter.java
src/ch/blinkenlights/android/vanilla/FileUtils.java
src/ch/blinkenlights/android/vanilla/LibraryActivity.java
src/ch/blinkenlights/android/vanilla/LibraryPagerAdapter.java
src/ch/blinkenlights/android/vanilla/MediaAdapter.java
src/ch/blinkenlights/android/vanilla/SortableAdapter.java

Tested all sorting types * reverse + save/restore setting.
Screenshot:
-> #305

Implement sorting for files tab

---

build.gradle
gradle/wrapper/gradle-wrapper.properties
res/values/translatable.xml
src/ch/blinkenlights/android/vanilla/LibraryActivity.java
src/ch/blinkenlights/android/vanilla/PlaybackService.java
src/ch/blinkenlights/android/vanilla/SongTimeline.java

Also some typos and small fixes.
- Update Gradle and build plugin versions as AS requires
- Fix incorrect and misleading descriptions

Jump to song in queue if picked just one

---

.gitignore
res/values/translatable.xml
src/ch/blinkenlights/android/medialibrary/MediaMetadataExtractor.java
src/ch/blinkenlights/android/vanilla/PlaybackService.java

Populate missing Artist/AlbumArtist values from each other.
Make sure that repeatedly playing the queue to completion with the "No repeat" setting plays it again completely, not just the last track.

Implement fixes for my favorite pet peeves in Vanilla

---

app/src/main/java/ch/blinkenlights/bastp/ID3v2File.java

This is a great project! I noticed that it wasn't picking up some of my mp3 files, and figured out that the tag reader doesn't support ID3v2.2.
This patch adds at least partial support for ID3v2.2 (also known as ID3v2-0, ID3v2.0, ...). 2.2 has a 3-digit tag name and a 3-digit unsigned length. There might be other significant differences but this was sufficient to make my ID3v2.2-tagged files work.

Add support for ID3v2.2 headers

---

README.md
app/build.gradle
build.gradle
gradle/wrapper/gradle-wrapper.properties

Upgrade Gradle, add annotations support and .editorconfig.

Gradle upgrade

---

app/src/main/java/ch/blinkenlights/android/vanilla/DraggableRow.java
app/src/main/java/ch/blinkenlights/android/vanilla/PlaylistAdapter.java
app/src/main/java/ch/blinkenlights/android/vanilla/ShowQueueAdapter.java
app/src/main/java/ch/blinkenlights/android/vanilla/Song.java
app/src/main/res/layout/draggable_row.xml

This partially addresses https://github.com/vanilla-music/vanilla/issues/647

Show song durations in queue (by adding a TextView)

---

app/src/main/java/ch/blinkenlights/android/vanilla/CoverBitmap.java
app/src/main/java/ch/blinkenlights/android/vanilla/CoverCache.java
app/src/main/java/ch/blinkenlights/android/vanilla/PlaybackService.java
app/src/main/java/ch/blinkenlights/android/vanilla/PrefDefaults.java
app/src/main/java/ch/blinkenlights/android/vanilla/PrefKeys.java
app/src/main/res/values/translatable.xml
app/src/main/res/xml/preference_coverart.xml

Though not intended might be a solution for issue #713,

A patch to add support for covers stored in the media files ID3Tag.

---

app/src/main/java/ch/blinkenlights/android/vanilla/PlaybackService.java
app/src/main/java/ch/blinkenlights/android/vanilla/RemoteControlImplICS.java
app/src/main/java/ch/blinkenlights/android/vanilla/RemoteControlImplLp.java

report the current song's position in the queue to the remote control;
report the current song's playback position to the remote control.

Implement some of the features present in Google Play Music:

---

app/src/main/java/ch/blinkenlights/android/medialibrary/MediaLibraryBackend.java
app/src/main/java/ch/blinkenlights/android/medialibrary/MediaSchema.java
app/src/main/java/ch/blinkenlights/android/vanilla/MediaAdapter.java

This addresses https://github.com/vanilla-music/vanilla/issues/647#issuecomment-419882367

Display durations in albums tab

---

app/src/main/java/ch/blinkenlights/android/vanilla/MediaButtonReceiver.java
app/src/main/java/ch/blinkenlights/android/vanilla/RemoteControlImplLp.java

Fix #873: support "stop" media button action.

Add stop to allowed actions.

---

app/src/main/java/ch/blinkenlights/android/vanilla/PreferencesActivity.java

There is a bug in https://github.com/vanilla-music/vanilla/pull/935 that causes crash. This fixes the crash.

Fix a bug in https://github.com/vanilla-music/vanilla/pull/935.

---

app/src/main/java/ch/blinkenlights/android/vanilla/CoverCache.java

Fixes some comments. Found these issues while diving into the code.

Fix comments within CoverCache class.
