res/values/translatable.xml, src/ch/blinkenlights/android/vanilla/PlaybackActivity.java, src/ch/blinkenlights/android/vanilla/PlaybackService.java, src/ch/blinkenlights/android/vanilla/ShowQueueActivity.java, src/ch/blinkenlights/android/vanilla/SongTimeline.java
TODO @adrian-bl :
- `empty_queue` string already exists (should be renamed probably)
- `clear_queue` should be renamed to `dequeue_rest` and changed to "Dequeue rest"
=> add "Empty queue" option in Queue activity

src/ch/blinkenlights/bastp/ID3v2File.java
As per http://id3.org/id3v2.4.0-structure section 4, the frame size field is a syncsafe integer, and reading without first converting is incorrect.
I have an MP3 file to demonstrate that the current behavior is incorrect and that my patch fixes it, but I'm not sure where to upload it (also, this is my first pull request, so let me know if I did something wrong).
=> Fix parsing of long frame lengths

src/com/mobeta/android/dslv/DragSortController.java
This fixes a rare crash on Samsung Galaxy S6 devices. The null arguments
appear to be caused by the GestureDetector not receiving an ACTION_DOWN
event before receiving an ACTION_MOVE event.
As we are unable to reproduce it, this commit work around the issue. It
might cause some scrolling issues in the cases that cause the issue, but
better than crashing.
=> DragSortController: Check for null MotionEvent arguments (#202)

src/com/mobeta/android/dslv/DragSortController.java
This reverts commit 7835436a3553f36e6457f8900ac9a5763b2bfbec.
Commit 7835436a attempted to fix the rare DSLV crash described in #113
by passing all touch events to the gesture detector. This includes
touches that occur when the drag is disabled or the list view wants to
intercept the event, and so is marginally undesirable. Also a factor is
that the DSLV code is taken from a third-party project, and so should be
kept as consistent as possible with upstream.
The attempt appears to not have worked, so a more direct workaround was
implemented in commit 4556d50ed, making 7835436a redundant. This commit
reverts 7835436a.
=> Revert "Attempt to fix #113"

src/ch/blinkenlights/android/vanilla/CoverView.java
Creating a bitmap with 0 width or height will cause a fatal exception.
A check was added in commit 2149745, but there are still some crashes
(e.g. issue #267). This commit replicates that check directly before the
creation of the bitmap.
=> Check width and height > 0 before generating bitmap

src/ch/blinkenlights/android/vanilla/MediaAdapter.java, src/ch/blinkenlights/android/vanilla/MediaUtils.java
Previously, genres without any songs associated with them would appear
in the Library genre list.
This commit adds a new query for genres that excludes these empty genres.
This partially fixes issue #286 (empty genres cannot be deleted) -
genres still can't be deleted, but the empty ones will no longer appear.
=> Exclude empty genres from genre list

AndroidManifest.xml
Hi Adrian,
Long time no see, Vanilla is becoming increasingly popular within the MirrorLink community to listen to local media whilst in their car, using RockScout (http://www.mirrorlink.com/apps/Vanilla%20Music%20with%20RockScout).
We have now an option to enable RockScout to be used as a front-end out of the car, if the media source allows for it.
Here's the patch that indicates Vanilla's willingness to fully participate in the RockScout experience, let me know if you have any concerns with it.
Best regards,
Laurent
=> MirrorLink: allow RockScout remote access outside of a Car

res/layout/full_playback_alt.xml, res/values/translatable.xml, src/ch/blinkenlights/android/vanilla/FullPlaybackActivity.java
This pull commit displays the path of the currently playing file in the extended playing view. It could be useful for broken tags, finding the file quickly etc.. Unfortunately my Android and Java knowledge is close to zero, so I can't do much more (like not displaying the library path or only displaying the necessary characters of each folder to shorten the displayed string).
=> Add path to extended currently playing view

src/ch/blinkenlights/android/vanilla/PlaybackService.java
Hi Adrian,
Here's a patch that fixes the PlaybackService ignoring result of requestAudiFocus before (re-……)starting playback, and also another issue where getting loss_transient twice would prevent playback from resuming where audio_focus_gain is next received
Cheers,
Laurent.
=> Found a couple of AudioFocus issues during our internal testing

Android.mk, CleanSpec.mk, res/layout/filebrowser_content.xml, res/layout/sdscanner_fragment.xml, res/layout/seekbar_pref.xml, res/values/untranslatable.xml
Also workaround build errors about missing localisation of empty strings
Change-Id: I359bee2019eee7bf1bf59107bbd68cc2a0ee1dc8
Vanilla: Cleanup Android.mk
Change-Id: Icac01fa7bc89b32ecc45ca8991fcb19d0db5baf3
=> Vanilla: Add Tools to build in Android tree

build.gradle, res/xml/preference_audio.xml, res/xml/preference_misc.xml, res/xml/preference_replaygain.xml, res/xml/preference_shake.xml, resNightly/values/translatable.xml
@adrian-bl , please use this instead of nightly script
```bash
./gradlew assembleNightly
```
Feel free to change at will (e.g. hostname can be added, etc)
- Does not require moves
- Does not change inner strings, allowing plugins to work in Nightly
- fixes vanilla-music/vanilla-music-tag-editor/issues/4
=> Add less-intrusive nightly configuration for gradle

src/ch/blinkenlights/android/vanilla/PlaybackService.java
Revised version of pull request #600.
Separate public and private notifications are created.
Presentation depends on Android security.
No settings within Vanilla are added.
Tested on Android 7.1 (LineageOS, real device).
I tried testing using the Android emulator for Android 4.X using Android Studio 2.3.2 (Linux and Windows).
However, I was unable to convince Vanilla to find music files (don't know why).
=> Mark notifications showing media content as private.

src/ch/blinkenlights/android/vanilla/CoverCache.java
Windows Media Player saves album covers in AlbumArt* files. Since 2011
Android has considered them as non-media files[1] and hasn't shown in
the Gallery application.
[1] https://android.googlesource.com/platform/frameworks/base/+/ade06df0fe3499d66ee5cc29071d41445d1091fa
=> Explicitly accept album art as saved by Windows Media Player

src/ch/blinkenlights/android/vanilla/MirrorLinkMediaBrowserService.java
Hello.
We are working on the RockScout which using the Vanilla Music as media provider. We noticed one issue which should be fixed after this changes.
To reproduce this issue we need app which using MediaBrowserService (for example the RockScout)
**Steps to reproduce:**
1. Force stop the Vanilla Music and the RockScout app.
2. Open the RockScout.
3. Select Vanilla Music provider, then click "Now Playing"
4. Click play.
**Result:**
Music is playing but missing metadata.
After click next/prev song everything is ok. This issue exist only at first connection to MediaBrowserService when the Vanilla Music isn't running.
=> Fix missing metadata at start using MediaBrowserService

app/src/main/java/ch/blinkenlights/android/medialibrary/MediaLibrary.java
The media/audio folder can be used as an alternative combined folder to add custom sounds to various android choosers.
This folder may hold for example the following subdirectories:
* alarms (/sdcard/Alarms alternative)
* notifications (/sdcard/Notifications alternative)
* ringtones (/sdcard/Ringtones alternative)
* ui (dont know if /sdcard/Ui is also such a directory)
All of these are scanned by Android in the same way like the other special directories.
As they hold e.g. click or short alarm sounds or like that they are not needed in music player ;).
=> Add "media/audio" to library default blacklist

.editorconfig, README.md, app/build.gradle
Annotations support allows making code look cleaner (e.g. `@NonNull` or `@Nullable` etc. JSR-305). It is not specific to Android Studio and is used during compilation.
I have a sane Android Studio editor, and even though it automatically detects coding conventions already present in the sources and keeps my changes consistent with them, it pops a yellow warning bar on top of the text editor telling me that it replaced spaces with tabs to follow the document's formatting style but that does not match my editor preferences.
.editorconfig is the clean way to avoid any such inconsistencies and tell any sane editor what are the project's preferences that should override any globally configured user's preferences.
This "clutter" is truly minimal and so not worth avoiding.
=> Editor config and annotations

app/src/main/java/ch/blinkenlights/android/vanilla/LibraryActivity.java, app/src/main/res/values-de/translatable.xml, app/src/main/res/values/translatable.xml, app/src/main/res/values/untranslatable.xml
Like with the expand action it will first try to expand a selected item. If the item can't be expanded it will use play all instead of play.
So when you select a song from the middle of an album the queue will contain that song and all remaining songs from that album.
=> Add library action expand or play all. Implements #488.

app/src/main/java/ch/blinkenlights/android/vanilla/PlaybackService.java
In this section of code, none of my music has Android music IDs. I'm guessing this is because none of it is in Android's media database. I don't see any reason not to include track, album and artist in the broadcast when this is the case.
As it is now, these details aren't in the broadcasts on my phone, so my scrobbler cannot scrobble my plays.
=> Include song title, ablum and artist in scrobble broadcast even when there is no Android media ID.

app/src/main/java/ch/blinkenlights/android/vanilla/PrefDefaults.java, app/src/main/java/ch/blinkenlights/android/vanilla/PrefKeys.java, app/src/main/java/ch/blinkenlights/android/vanilla/ShowQueueFragment.java, app/src/main/res/values/translatable.xml, app/src/main/res/xml/preference_library.xml
Adds a new setting to scroll the queue to the new song after a song
change. The new song will be at the top of the view.
Kind of fixes #798
=> Add option to scroll to new track on song change

app/src/main/java/ch/blinkenlights/android/vanilla/PlaybackActivity.java, app/src/main/java/ch/blinkenlights/android/vanilla/PluginUtils.java, app/src/main/res/values/translatable.xml
In Android Oreo we can't use services without bringing them to the
foreground, i.e. showing icon and following specified lifecycle.
After some consideration the new way was implemented for plugin system.
Plugins will no longer have bound service and instead will do everything
required from within their activities. All background logic that
previously resided in services will now be performed before the activity
has even shown its window. This greatly reduces complexity and cost
associated with bringing service model in accordance with Oreo
guidelines. The only downside to this approach is small flickering
or pause in emulators as activities still expect to show themselves
on start instead of disappearing again.
=> Update plugin waking code, fix crash on Oreo devices

app/src/main/java/ch/blinkenlights/android/vanilla/LibraryPagerAdapter.java
The change adds interactive check to see if smooth scroll is actually
needed. If user doesn't see the library screen there's no point in
doing smooth scroll.
Besides, for old Android versions (like 4.x)
View.getFirstVisiblePosition, View.getLastVisiblePosition calls are
working only if view is currently visible.
=> Don't use smooth scroll if user doesn't see it

app/src/main/java/ch/blinkenlights/android/vanilla/TrackDetailsDialog.java
This gets rid of the blank title section in the dialog when shown on the playlist activity and on older versions of Android.
This addresses https://github.com/vanilla-music/vanilla/pull/849#issuecomment-430756661
=> Set STYLE_NO_TITLE for TrackDetailsDialog

app/src/main/AndroidManifest.xml
Since 7c9731e05b4e5ebb92f5fe59519709606ba50ef9 targets API 28, playing a song will crash on Android 9 unless we declare this permission.
See https://developer.android.com/about/versions/pie/android-9.0-changes-28#fg-svc
=> Add FOREGROUND_SERVICE permission

app/src/main/java/ch/blinkenlights/android/vanilla/FullPlaybackActivity.java, app/src/main/java/ch/blinkenlights/android/vanilla/PluginUtils.java, app/src/main/res/drawable/plugin.xml
We are now fully switched to activity-based plugin
start system, so we don't need to start service or
wake activity anymore. Delete relevant part.
If the additiona; information is needed about the
plugin we can dig it out from its broadcast receiver.
Also, add quick "Plugins" button to the full playback
activity so there are only 2 clicks away from any plugin.
=> Speedup plugin search, add quick plugin button, fixes #859

app/src/main/java/ch/blinkenlights/android/vanilla/FileSystemAdapter.java, app/src/main/java/ch/blinkenlights/android/vanilla/FileUtils.java, app/src/main/java/ch/blinkenlights/android/vanilla/MediaUtils.java, app/src/main/java/ch/blinkenlights/android/vanilla/PlaybackService.java, app/src/main/java/ch/blinkenlights/android/vanilla/PlaylistObserver.java, app/src/main/java/ch/blinkenlights/android/vanilla/PrefDefaults.java, app/src/main/java/ch/blinkenlights/android/vanilla/PrefKeys.java, app/src/main/res/values/translatable.xml, app/src/main/res/xml/preference_playlist.xml
This change adds a new option within the playlists settings item to relativize file paths from the playlists directory e.g.
- Music file: /storage/emulated/0/Music/Song.mp3
- Playlist directory: /storage/emulated/0/Playlists/
- Resultant path: ../Music/Song.mp3
The path relativization solution is not completely general, since it will incorrectly relativize UNC paths on Windows and is not aware of the filesystem's case insensitivity (case insensitivity may be an issue for FAT32).
This should resolve #905.
=> [Issue #905] Add playlist path relativization option.

app/src/main/java/ch/blinkenlights/android/vanilla/FileUtils.java
When you have a music folder /music and a playlists folder /music/playlists , then reading a playlist with a song ../a.mp3 inside resolved to "/music/playlists/../a.mp3" , which broke the import operation. Using getCanonicalPath instead of getAbsolutePath fixes the issue, since the former resolves the URI to /music/a.mp3
=> Fix relative path resolution

app/src/main/java/ch/blinkenlights/android/vanilla/PreferencesActivity.java
Fixes #918 
This error occurs because the onClickOptionsMenu always returns to the library and overrides the default behavior. The default would be to use the appstack to decide which was the last activity and to return to that.
=> Remove onOptionsItemSelected to fix backbutton in settings

app/src/main/java/ch/blinkenlights/android/vanilla/FullPlaybackActivity.java, app/src/main/java/ch/blinkenlights/android/vanilla/LibraryActivity.java, app/src/main/java/ch/blinkenlights/android/vanilla/PlaybackActivity.java, app/src/main/java/ch/blinkenlights/android/vanilla/PluginUtils.java
Currently plugin searching still works in two stages, first it searches
for all plugin broadcast receivers and then waits for all the answers
to complete the plugin map. If any of plugins doesn't answer the call
this means all of them won't be shown and that's not very user-friendly.
The change simplifies plugin search to just package scan for specific
broadcast receivers. Android provides package name and app info for it.
We don't need any other info from plugins, so we don't need to wait for
broadcast roadtrip.
Further improvements:
* introduce meta-data and uses-feature tags in
plugin manifests and get rid of broadcast receiver completely.
* Implement view in settings activity with list of installed plugins
=> Simplify plugin package search. Fix plugin detection.

app/src/main/java/ch/blinkenlights/android/vanilla/PreferencesActivity.java
Previously, hitting back button after opening Equalizer or Play when plugged will exit the whole setting. Now back button will take us back to Audio.
=> Fixed back button behavior in Setting-Audio

app/src/main/java/ch/blinkenlights/android/vanilla/LibraryActivity.java
This makes it more consistent with the FancyMenu for tracks in the
queue, where Details appears before Remove.
=> Move Details before Delete in LibraryActivity's FancyMenu

app/src/main/java/ch/blinkenlights/android/vanilla/CoverBitmap.java, app/src/main/res/values-v21/theme-amoled_dark.xml, app/src/main/res/values-v21/theme-blue_dark.xml, app/src/main/res/values-v21/theme-blue_light.xml, app/src/main/res/values-v21/theme-grey_dark.xml, app/src/main/res/values-v21/theme-grey_light.xml, app/src/main/res/values-v21/theme-orange_dark.xml, app/src/main/res/values-v21/theme-orange_light.xml, app/src/main/res/values-v21/theme-red_dark.xml, app/src/main/res/values-v21/theme-red_light.xml, app/src/main/res/values-v21/theme-standard_dark.xml, app/src/main/res/values-v21/theme-standard_light.xml, app/src/main/res/values/attrs.xml, app/src/main/res/values/theme-standard.xml, app/src/main/res/values/tiles_colors.xml, generate-themes.pl
=> Use darker colors for artist images

app/src/main/AndroidManifest.xml
This is a temporary workaround to buy more time to see if a better
solution can be worked on for Android 10's scoped storage limitations.
=> Use android:requestLegacyExternalStorage

app/src/main/java/ch/blinkenlights/android/vanilla/FileUtils.java
When resolving relative paths such as `../../storage/emulated/0/` the symlinks will be read and parent paths removed, in that order. This results in paths from an `/sdcard` symlink producing unexpected relative paths e.g.`/sdcard/../storage/emulated/0/test.mp3` resolves to `/storage/emulated/storage/emulated/0/test.mp3` instead of `/storage/emulated/0/test.mp3`.
Because `relativize` does not canonicalize, this can also result in Vanilla producing paths it cannot reimport.
This change fixes path resolution to remove parent directories, without following symbolic links.
Some unscientific tests on my device indicate this also improves playlist import performance.
This should partially resolve issue #966.
=> Fix playlist path resolution for symlinked paths.

app/src/main/java/ch/blinkenlights/android/vanilla/LibraryPagerAdapter.java
When the tracks tab is available, the genre tab is correctly expanded following the expected sequence (genre -> artist -> album -> track). But if the tracks tab is disabled, then the genre is not expanded even if artist and/or album tabs are enabled. Instead, it adds all tracks for that genre to the playlist.
This is because the expansion for genre is currently based on detecting only the tracks tab, ignoring the presence of the artists and/or albums tabs. This PR adds these conditions so the genre is correctly expanded in this case.
=> Fix genre tab expansion when tracks tab is no present

app/src/main/java/ch/blinkenlights/android/vanilla/MediaUtils.java
Currently when trying to add a directory of music-files to the queue via "Play all", 
it often happens that Vanilla Music reports "0 tracks added to the queue". 
When debugging, I found that this happens when the files are not contained 
in the music database yet.
Currently only single files are handled, but it is useful to also
do this for directories by recursively adding all contained files.
=> Support adding all files from a directory

Makefile.internal, app/src/main/res/layout/full_playback.xml, app/src/main/res/values/dimens.xml
As phone displays adopt taller aspect ratios & get rid of thick bezels/chins, it becomes much more challenging to operate playback one-handed on the go without a painful finger stretching.
This was not a problem for a very long time on my trusty but rusty Motorola G3; now I have switched to Motorola G52, where my thumb naturally lands on a seekbar.
Below are some pictures just for comparison.
_Current version_
_Modified version. The playback controls bar is a little bit raised above navigation bar._
You might reasonably ask how do I use navigation bar then, and the answer would be: _I suffer. A lot. Or just use a capacitive stylus, but that requires both hands._
Please feel free to close this pull request if it does not meet any requirements.
=> Adjusted controls layout for taller displays

app/src/main/AndroidManifest.xml
Fixes https://github.com/vanilla-music/vanilla-headphone-detector/issues/20. Introduced in c3175f756d8726fd7dc6ecb26877c89ef7ac1080.
Not allowing the service to be exported leads to permission denied by headphone detector which in turn crashes as described in the issue linked above.
All credits go to @klaufir216 for explaining the bug, I just created the PR.
=> Export PlaybackService
